UI updates for Description Component
rpt12-knightrider/sm-service pull request #10
Opened 2019-04-23 03:05 UTC by steven-miller

* Added `react-popper` and configured for placement of popups
* Added ratings details popup
* Added calculations to ratings details popup
* Added "Stores" button dropdown

2019-04-23 06:08 UTC, MuhammadJamaluddin requested changes

2019-04-23 06:08 UTC, MuhammadJamaluddin commented on client/src/description.jsx
> +import RatingsPopup from './ratingsPopup.jsx';
Would remove the `jsx` extension to conform with the style guide & include this within the `modules.exports` object in the `.eslintrc.js` file:
```
resolve: {
    extensions: ['.js', '.jsx'],
  },
```
This will make `webpack ` handle the extensions for you...

2019-04-23 06:08 UTC, MuhammadJamaluddin commented on client/src/ratingsPopup.jsx
> +                  Rating details
you may wanna fix the `eslint` complaints about the new line issue.

2019-04-23 06:08 UTC, MuhammadJamaluddin commented on client/src/ratingsPopup.jsx
> +import { Manager, Reference, Popper, Arrow } from 'react-popper';
Looks like `Arrow` is never used. I'd remove it unless you plan to use it lately.

2019-04-23 06:08 UTC, MuhammadJamaluddin commented on client/src/ratingsPopup.jsx
> +      isOpen: !this.state.isOpen
This is really problematic *even it works* (refer to these subsequent questions in the official documentation starting from this question https://reactjs.org/docs/faq-state.html#why-is-setstate-giving-me-the-wrong-value for knowing the fix (an updater function) & for more details).

2019-04-24 01:56 UTC, steven-miller commented on client/src/description.jsx
> +import RatingsPopup from './ratingsPopup.jsx';
I could not figure out why I had to include the `jsx` - thank you, this clears it up!

2019-04-24 02:03 UTC, steven-miller commented on client/src/ratingsPopup.jsx
> +      isOpen: !this.state.isOpen
Good catch - didn't even think about this, since a double toggle in close proximity is rare but not impossible.

2019-04-24 02:03 UTC, merged